FROM openjdk:11
CMD ["npx", "tailwindcss", "build", "html/style/input.css", "-o", "html/style/output.css"]


COPY ./Run ./QuorumDatabase
COPY ./Run/Default.jar ./QuorumDatabase/QuorumDatabase.jar
RUN rm ./QuorumDatabase/Default.jar
WORKDIR /QuorumDatabase
