FROM openjdk:11
# ./tailwindcss -i html/style/input.css -o html/style/output.css
CMD ["./tailwindcss", "-i", "html/style/input.css", "-o", "html/style/output.css"]

# RUN ./QuorumDatabase/tailwindcss -i html/style/input.css -o html/style/output.css
COPY ./Run ./QuorumDatabase
COPY ./Run/Default.jar ./QuorumDatabase/QuorumDatabase.jar
RUN rm ./QuorumDatabase/Default.jar
WORKDIR /QuorumDatabase
