FROM openjdk:11
COPY ./Run ./QuorumDatabase
COPY ./Run/Default.jar ./QuorumDatabase/QuorumDatabase.jar
COPY ./html/Libraries ./QuorumDatabase/Libraries
COPY ./html/libraries.html ./QuorumDatabase/libraries.html
RUN rm ./QuorumDatabase/Default.jar
WORKDIR /QuorumDatabase
